version: '3.8'
services:
  postregsdb:
    image: postgres:latest
    restart: always
    environment:
      - DATABASE_NAME=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '6543:5432'
    volumes:
      - postregsdb:/var/lib/postgresql/data

  api:
    container_name: applift_api
    build:
      context: ./
    image: applift_api
    depends_on:
      - postregsdb
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=pg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    links:
      - postregsdb
    volumes:
      - './:/src'
    networks:
      - net


volumes:
  postregsdb:
    driver: local

networks:
  net:
    driver: bridge