name: Django Testing

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py test