name: Django Testing

on:
  push:
    branches:
      - master

jobs:
  pytest:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          DATABASE_NAME: postgres

        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5
      - name: Pytest
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py test
